name: dice
version: 1.4.0
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice
environment:
  sdk: '>=0.7.5'
dependencies:
  meta: '>=0.7.5'
dev_dependencies:
  unittest: any
