name: dice
version: 1.3.1
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice
environment:
  sdk: '>=0.7.1'
dependencies:
  meta: '>=0.7.1'
dev_dependencies:
  unittest: any
