name: dice
version: 1.1.5
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice
environment:
  sdk: '>=0.5.20'
dependencies:
  meta: '>=0.5.20'
dev_dependencies:
  unittest: any
