name: dice
version: 1.4.3
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice
environment:
  sdk: '>=0.8.7'
dependencies:
  meta: '>=0.8.7'
dev_dependencies:
  unittest: any
