name: dice
version: 1.0.2
author: Lars Tackmann <lars@solvr.io>
homepage: https://github.com/ltackmann/dice
description: Lightweight dependency injection framework for Dart.
dependencies:
  meta: any
dev_dependencies:
  unittest: any 
