name: dice
version: 1.1.1
author: Lars Tackmann <lars@solvr.io>
homepage: https://github.com/ltackmann/dice
description: Lightweight dependency injection framework for Dart.
dependencies:
  meta: '>=0.4.0'
dev_dependencies:
  unittest: any 
environment:
  sdk: ">=0.4.7"
