name: dice
version: 1.5.0
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  meta: '>=0.8.8 < 0.10.0'
dev_dependencies:
  unittest: any
