name: dice
version: 1.6.4
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  meta: "^0.8.8"
dev_dependencies:
  test: any
